### PR TITLE
Updated min iOS version to iOS 13

### PR DESCRIPTION
**Pull request by aaron-russell**

### CODE REVIEW

**Comment by mahnuh** [comment]
Hi, can you tell me why this is necessary?

**Comment by aaron-russell** [comment]
The latest version of capacitor only supports iOS 13 and above

**Comment by mahnuh** [comment]
@aaron-russell that is correct, but is there an actual issue? Because the plugin works just fine for me in a Capacitor 4 app. I want to maintain backwards compatibility, please see [this comment](https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency/pull/10#issuecomment-1217906736).
If there actually is an issue with the current version of the plugin and the current version of Capacitor, please provide me with more information.

**Comment by aaron-russell** [comment]
@mahnuh Every time I run an archive, it fails initially, saying the build version on this plug-in is set to 12 and not 13. Not a huge deal, I know, but when archiving in CI/CD this could be a problem.

**Comment by mahnuh** [comment]
@aaron-russell interesting... archiving just went without issues for my demo app. How do you exactly run archive?

**Comment by aaron-russell** [comment]
@mahnuh sorry for the late reply. I run it in Xcode.

Screenshot of Xcode with the error showing

I'm having to change 12 to 13 every time I archive.

**Comment by mahnuh** [comment]
Hi @aaron-russell, sorry for the really long delay. I thought I replied already. So, can you please check [this demo app](https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency-demo-app) with Capacitor 5? I am able to build and archive the app without any issue.

**Comment by jcesarmobile** [comment]
Does your app have this in the `ios/App/Podfile`?
```
// first line
require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

// last lines
post_install do |installer|
  assertDeploymentTarget(installer)
end
```

That should force your Capacitor 4-5 app to target iOS SDK 13 or newer on your app and all your plugins, so the proposed change shouldn't be necessary. 
Maybe you missed that step on the Capacitor 3 to 4 migration guide
https://capacitorjs.com/docs/updating/4-0#raise-ios-deployment-target

**Comment by mahnuh** [comment]
I'm closing this PR now. Please feel free to open an issue if there still is a problem and you can provide code to reproduce the issue.

**Pull request closed without merging**
