### PR TITLE
feat(): update to capacitor4

### PR DESCRIPTION
**Pull request by rdlabo**
follows the changes in https://github.com/ionic-team/create-capacitor-plugin/commit/03027bf603626ebfdba084cb9d9a1a359d008554

Thanks.

### CODE REVIEW

**Comment by mahnuh** [comment]
Hi @rdlabo, does this still work with Capacitor 3 apps or are theese breaking changes? As I'm on vacation right now I'm not able to check this myself.

**Comment by rdlabo** [comment]
@mahnuh Hi, thanks for review.

> does this still work with Capacitor 3 apps

No. targetSDK is changed in iOS and Android. Capacitor 3 > 4 is breaking changes.

**Comment by mahnuh** [comment]
Hi @rdlabo, I'm not happy with dropping support for Capacitor 3 when it seams that the only issue is the peerDependencies version of Capacitor 3.x. Could you please verify with the just published version 2.0.2-beta.0 of this plugin if this solves your problem and works well with a Capacitor 4 app?

**Comment by mahnuh** [comment]
Hi @rdlabo, please give 2.0.2-beta.1 of this plugin a try. I just verified with a Capacitor 4.0.1 app and everything works as expected.

**Comment by mahnuh** [comment]
Closing this as the plugin ([v2.0.2](https://github.com/mahnuh/capacitor-plugin-app-tracking-transparency/releases/tag/v2.0.2)) now is compatible with Capacitor 4 while maintaining backwardcompatibility to Capacitor 3.

**Pull request closed without merging**
